version: '3.7'

services:
    backend:
        container_name: kr-backend
        image: ghcr.io/rkorom/backendforfrontend:latest
        restart: 'always'
        ports:
            - '3000:3000'
            - '8000:8000'
            - '8001:8001'
            - '8002:8002'
            - '8003:8003'
            - '8004:8004'
            - '8005:8005'
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
    watchtower:
        container_name: kr-watchtower
        image: containrrr/watchtower:latest
        restart: 'always'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WATCHTOWER_CLEANUP: 'true'
            WATCHTOWER_POLL_INTERVAL: '300' # seconds
        command: --label-enable
